name: Deploy Hotel Booking Pipeline

on:
  push:
    branches:
      - main  # deploy all envs from main branch

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install databricks-cli dab
      - run: databricks configure --token <<< "$DATABRICKS_HOST\n$DATABRICKS_TOKEN"
      - run: dab deploy --file databricks.yml --job bronze_dev --job silver_dev --job gold_dev

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v3
      - run: pip install databricks-cli dab
      - run: databricks configure --token <<< "$DATABRICKS_HOST\n$DATABRICKS_TOKEN"
      - run: dab deploy --file databricks.yml --job bronze_stage --job silver_stage --job gold_stage

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    steps:
      - uses: actions/checkout@v3
      - run: pip install databricks-cli dab
      - run: databricks configure --token <<< "$DATABRICKS_HOST\n$DATABRICKS_TOKEN"
      - run: dab deploy --file databricks.yml --job bronze_prod --job silver_prod --job gold_prod
